#/**************************************************************************
# * Copyright 2011, Freescale Semiconductor, Inc. All rights reserved.
# ***************************************************************************/
#/*
# * File:	makefile
# *
# * Authors:	Hemant Agrawal <hemant@freescale.com>
# *
# *
# */
.PHONY: all
all: build

build:
	make -w -C linux -f makefile

#--------------------------------------------------------------
.PHONY: clean
clean:
	make -w -C linux -f makefile clean
