#/**************************************************************************
# * Copyright 2009-2010 by Freescale Semiconductor, Inc.
# * All modifications are confidential and proprietary information
# * of Freescale Semiconductor, Inc. ALL RIGHTS RESERVED.
# ***************************************************************************/
#/*
# * File:	Makefile
# *
# */

#------------------------------------------------------------------------------
#  Include Definitions
#------------------------------------------------------------------------------
.PHONY: all
all: build

build:
#	make -w -C driver -f Makefile

#--------------------------------------------------------------
.PHONY: clean
clean:
#	make -w -C driver -f Makefile clean

